import { Gauge, Wrench, Battery, Snowflake, CircleGauge, Fuel, Search, ClipboardCheck, FileCheck2, ThumbsUp, ShieldCheck, CreditCard, Clock, BadgePercent } from "lucide-react";
import { autoRepair as img, headshots } from "./images";
import type { DemoLocale } from "@/lib/demo-i18n/LanguageContext";

export const autoRepairShared = {
  icon: Wrench,
  theme: { accent: "#ef4444", accent2: "#0ea5e9" },
  phone: "(514) 555-0163",
  towingPhone: "(514) 555-0911",
  email: "service@garage-demo.com",
  address: "2210 Boulevard Industriel, Laval, QC H7S 1P8",
};

export const autoRepairContent: Record<DemoLocale, ReturnType<typeof buildFr> | ReturnType<typeof buildEn>> = {
  fr: buildFr(),
  en: buildEn(),
};

function buildFr() {
  return {
    businessName: "Garage",
    tagline: "Réparation et entretien automobile complet pour toutes marques et modèles — diagnostics honnêtes, prix justes.",
    ctaLabel: "Prendre rendez-vous",
    navLinks: [
      { label: "Services", href: "#services" },
      { label: "Diagnostics", href: "#diagnostics" },
      { label: "Réparations", href: "#repairs" },
      { label: "Forfaits", href: "#packages" },
      { label: "Avis", href: "#reviews" },
      { label: "Rendez-vous", href: "#booking" },
      { label: "Contact", href: "#contact" },
    ],
    hero: {
      eyebrow: "Techniciens certifiés ASE",
      title: "Une réparation automobile honnête, en qui vous pouvez avoir confiance",
      subtitle: "Diagnostics de pointe et techniciens certifiés pour toutes marques et modèles — avec des prix transparents, toujours.",
      imageId: img.heroWide,
      primaryCta: { label: "Prendre rendez-vous", href: "#booking" },
      secondaryCta: { label: "Voir les services", href: "#services" },
    },
    servicesEyebrow: "Ce que nous réparons",
    servicesTitle: "Services de réparation automobile complets",
    servicesDescription: "Des techniciens certifiés pour toutes marques et modèles, importées et nationales.",
    services: [
      { icon: Gauge, title: "Service de freins", description: "Remplacement de plaquettes et disques, purge du liquide de frein et inspection complète." },
      { icon: Wrench, title: "Moteur et transmission", description: "Diagnostics moteur complets, mises au point et service de transmission pour toutes marques." },
      { icon: Battery, title: "Électrique et batterie", description: "Test et remplacement de batterie, alternateur, démarreur et diagnostics de câblage." },
      { icon: Snowflake, title: "Climatisation et chauffage", description: "Recharge de climatisation, réparation du système de chauffage et diagnostics de climatisation." },
      { icon: CircleGauge, title: "Pneus et alignement", description: "Rotation, équilibrage, alignement des roues et installation de pneus neufs." },
      { icon: Fuel, title: "Changement d'huile et entretien", description: "Changements d'huile synthétique complète et entretien selon les recommandations du fabricant." },
    ],
    diagnosticsEyebrow: "Diagnostics du véhicule",
    diagnosticsTitle: "Comment nous diagnostiquons le problème",
    diagnosticsDescription: "Transparent, étape par étape — vous savez toujours ce qui se passe avec votre véhicule.",
    diagnosticsSteps: [
      { icon: Search, title: "Inspection initiale", description: "Une inspection visuelle et informatique complète pour identifier la cause réelle, pas seulement les symptômes." },
      { icon: ClipboardCheck, title: "Diagnostic informatique", description: "Des outils de diagnostic de niveau constructeur pour cibler les codes d'erreur précis." },
      { icon: FileCheck2, title: "Rapport détaillé", description: "Vous recevez un rapport clair et détaillé avec photos avant que tout travail commence." },
      { icon: ThumbsUp, title: "Réparation approuvée", description: "Rien n'est fait sans votre accord — aucune surprise sur la facture, jamais." },
    ],
    repairsEyebrow: "Réparations majeures",
    repairsTitle: "Travaux de réparation spécialisés",
    repairs: [
      { icon: Wrench, title: "Réparation de moteur", description: "Des petites réparations aux reconstructions complètes." },
      { icon: Gauge, title: "Réparation de transmission", description: "Spécialistes des transmissions automatiques et manuelles." },
      { icon: CircleGauge, title: "Suspension et direction", description: "Amortisseurs, jambes de force et composants de direction." },
      { icon: Fuel, title: "Systèmes d'échappement", description: "Réparation de silencieux, convertisseur catalytique et échappement." },
    ],
    packagesEyebrow: "Forfaits d'entretien",
    packagesTitle: "Gardez votre véhicule performant",
    packagesDescription: "Choisissez le forfait d'entretien adapté à vos habitudes de conduite.",
    packages: [
      { name: "Entretien de base", price: "89 $", period: "/visite", features: ["Changement d'huile et filtre", "Inspection 21 points", "Vérification des pneus"], ctaLabel: "Réserver l'entretien de base" },
      { name: "Entretien standard", price: "179 $", period: "/visite", features: ["Tout de l'entretien de base", "Inspection des freins", "Appoint des liquides", "Test de la batterie"], highlighted: true, ctaLabel: "Réserver l'entretien standard" },
      { name: "Entretien premium", price: "289 $", period: "/visite", features: ["Tout de l'entretien standard", "Diagnostic complet", "Vérification de l'alignement", "Vérification de la climatisation"], ctaLabel: "Réserver l'entretien premium" },
    ],
    reviewsEyebrow: "Avis clients",
    reviewsTitle: "Ce que disent les automobilistes",
    reviews: [
      { quote: "Premier garage à me montrer des photos du problème réel avant de me facturer quoi que ce soit. Une honnêteté rafraîchissante.", name: "Karim Haddad", role: "Avis Google", avatarId: headshots.manGreyJacket, rating: 5 },
      { quote: "Rapide, prix justes, et ils expliquent vraiment ce qu'ils font. Mon nouveau garage de confiance.", name: "Julie Simard", role: "Avis Google", avatarId: headshots.womanCrewNeck, rating: 5 },
      { quote: "Ils ont diagnostiqué un problème que deux autres garages n'avaient pas trouvé. Ça m'a économisé des milliers de dollars.", name: "Anthony Ricci", role: "Avis Google", avatarId: headshots.manBlueBlazer, rating: 5 },
    ],
    bookingEyebrow: "Rendez-vous en ligne",
    bookingTitle: "Planifiez votre service",
    bookingDescription: "Choisissez un moment qui vous convient — nous confirmerons dans les prochaines heures.",
    bookingFields: [
      { type: "text" as const, name: "name", label: "Nom complet", placeholder: "Votre nom", required: true, span: 1 as const },
      { type: "tel" as const, name: "phone", label: "Téléphone", placeholder: "(514) 000-0000", required: true, span: 1 as const },
      { type: "text" as const, name: "vehicle", label: "Marque et modèle du véhicule", placeholder: "ex. Honda Civic 2019", required: true, span: 2 as const },
      {
        type: "select" as const,
        name: "serviceType",
        label: "Service requis",
        options: ["Changement d'huile", "Service de freins", "Diagnostics", "Transmission", "Pneus et alignement", "Autre"],
        span: 1 as const,
      },
      { type: "date" as const, name: "date", label: "Date préférée", span: 1 as const },
    ],
    bookingSubmitLabel: "Réserver mon rendez-vous",
    bookingSuccess: "Merci! Votre demande de rendez-vous a été reçue — nous confirmerons sous peu.",
    financingEyebrow: "Options de financement",
    financingTitle: "Des réparations adaptées à votre budget",
    financing: [
      { icon: CreditCard, title: "Financement à 0 %", description: "Disponible sur les réparations de plus de 500 $ pour les clients admissibles." },
      { icon: Clock, title: "Approbation le jour même", description: "Demande simple et rapide avec décision instantanée." },
      { icon: ShieldCheck, title: "Garantie de 12 mois", description: "Toutes les réparations sont garanties pièces et main-d'œuvre." },
      { icon: BadgePercent, title: "Rabais pour flottes", description: "Tarifs spéciaux pour les entreprises avec plusieurs véhicules." },
    ],
    contactEyebrow: "Visitez notre garage",
    contactTitle: "Contactez-nous",
    contactDescription: "Sans rendez-vous bienvenu pour les diagnostics — rendez-vous recommandé pour les réparations.",
    hoursNote: "Heures d'ouverture : lundi – samedi, 7 h 30 – 18 h",
    towingLabel: "Remorquage 24/7",
  };
}

function buildEn() {
  return {
    businessName: "Auto Repair",
    tagline: "Full-service auto repair and maintenance for all makes and models — honest diagnostics, fair pricing.",
    ctaLabel: "Book a Service",
    navLinks: [
      { label: "Services", href: "#services" },
      { label: "Diagnostics", href: "#diagnostics" },
      { label: "Repairs", href: "#repairs" },
      { label: "Packages", href: "#packages" },
      { label: "Reviews", href: "#reviews" },
      { label: "Booking", href: "#booking" },
      { label: "Contact", href: "#contact" },
    ],
    hero: {
      eyebrow: "ASE-Certified Technicians",
      title: "Honest auto repair you can trust",
      subtitle: "State-of-the-art diagnostics and certified technicians for every make and model — with upfront pricing, always.",
      imageId: img.heroWide,
      primaryCta: { label: "Book a Service", href: "#booking" },
      secondaryCta: { label: "View Services", href: "#services" },
    },
    servicesEyebrow: "What We Fix",
    servicesTitle: "Complete auto repair services",
    servicesDescription: "Certified technicians for every make and model, foreign and domestic.",
    services: [
      { icon: Gauge, title: "Brake Service", description: "Pad and rotor replacement, brake fluid flush, and full brake system inspection." },
      { icon: Wrench, title: "Engine & Transmission", description: "Complete engine diagnostics, tune-ups, and transmission service for all makes." },
      { icon: Battery, title: "Electrical & Battery", description: "Battery testing and replacement, alternator, starter, and wiring diagnostics." },
      { icon: Snowflake, title: "AC & Heating", description: "AC recharge, heating system repair, and climate control diagnostics." },
      { icon: CircleGauge, title: "Tires & Alignment", description: "Tire rotation, balancing, wheel alignment, and new tire installation." },
      { icon: Fuel, title: "Oil Change & Maintenance", description: "Full-synthetic oil changes and manufacturer-recommended maintenance schedules." },
    ],
    diagnosticsEyebrow: "Vehicle Diagnostics",
    diagnosticsTitle: "How we diagnose the problem",
    diagnosticsDescription: "Transparent, step-by-step — you always know what's happening with your vehicle.",
    diagnosticsSteps: [
      { icon: Search, title: "Initial Inspection", description: "A full visual and computer scan to identify the root cause, not just symptoms." },
      { icon: ClipboardCheck, title: "Computer Diagnostics", description: "OEM-level scan tools pinpoint exact fault codes across every vehicle system." },
      { icon: FileCheck2, title: "Detailed Report", description: "You get a clear, itemized report with photos before any work begins." },
      { icon: ThumbsUp, title: "Approved Repair", description: "Nothing happens without your sign-off — no surprise charges, ever." },
    ],
    repairsEyebrow: "Major Repairs",
    repairsTitle: "Specialized repair work",
    repairs: [
      { icon: Wrench, title: "Engine Repair", description: "From minor fixes to full rebuilds." },
      { icon: Gauge, title: "Transmission Repair", description: "Automatic & manual transmission specialists." },
      { icon: CircleGauge, title: "Suspension & Steering", description: "Shocks, struts, and steering components." },
      { icon: Fuel, title: "Exhaust Systems", description: "Muffler, catalytic converter & exhaust repair." },
    ],
    packagesEyebrow: "Maintenance Packages",
    packagesTitle: "Keep your vehicle running strong",
    packagesDescription: "Choose the maintenance plan that fits your driving habits.",
    packages: [
      { name: "Basic Care", price: "$89", period: "/visit", features: ["Oil & filter change", "21-point inspection", "Tire pressure check"], ctaLabel: "Book Basic Care" },
      { name: "Standard Care", price: "$179", period: "/visit", features: ["Everything in Basic", "Brake inspection", "Fluid top-up", "Battery test"], highlighted: true, ctaLabel: "Book Standard Care" },
      { name: "Premium Care", price: "$289", period: "/visit", features: ["Everything in Standard", "Full diagnostics scan", "Alignment check", "AC system check"], ctaLabel: "Book Premium Care" },
    ],
    reviewsEyebrow: "Customer Reviews",
    reviewsTitle: "What drivers say about us",
    reviews: [
      { quote: "First shop that's ever shown me photos of the actual problem before charging me a dime. Refreshingly honest.", name: "Karim Haddad", role: "Google Review", avatarId: headshots.manGreyJacket, rating: 5 },
      { quote: "Fast, fair pricing, and they actually explain what they're doing. My new go-to shop.", name: "Julie Simard", role: "Google Review", avatarId: headshots.womanCrewNeck, rating: 5 },
      { quote: "Diagnosed an issue two other shops couldn't find. Saved me thousands in unnecessary parts.", name: "Anthony Ricci", role: "Google Review", avatarId: headshots.manBlueBlazer, rating: 5 },
    ],
    bookingEyebrow: "Online Booking",
    bookingTitle: "Schedule your service",
    bookingDescription: "Pick a time that works for you — we'll confirm within a few hours.",
    bookingFields: [
      { type: "text" as const, name: "name", label: "Full Name", placeholder: "Your name", required: true, span: 1 as const },
      { type: "tel" as const, name: "phone", label: "Phone", placeholder: "(514) 000-0000", required: true, span: 1 as const },
      { type: "text" as const, name: "vehicle", label: "Vehicle Make & Model", placeholder: "e.g. 2019 Honda Civic", required: true, span: 2 as const },
      {
        type: "select" as const,
        name: "serviceType",
        label: "Service Needed",
        options: ["Oil Change", "Brake Service", "Diagnostics", "Transmission", "Tires & Alignment", "Other"],
        span: 1 as const,
      },
      { type: "date" as const, name: "date", label: "Preferred Date", span: 1 as const },
    ],
    bookingSubmitLabel: "Book My Appointment",
    bookingSuccess: "Thanks! Your booking request has been received — we'll confirm shortly.",
    financingEyebrow: "Financing Options",
    financingTitle: "Repairs that fit your budget",
    financing: [
      { icon: CreditCard, title: "0% Financing", description: "Available on repairs over $500 for qualified customers." },
      { icon: Clock, title: "Same-Day Approval", description: "Quick, simple application with instant decisions." },
      { icon: ShieldCheck, title: "12-Month Warranty", description: "All repairs backed by a full parts & labor warranty." },
      { icon: BadgePercent, title: "Fleet Discounts", description: "Special rates for businesses with multiple vehicles." },
    ],
    contactEyebrow: "Visit Our Shop",
    contactTitle: "Get in touch",
    contactDescription: "Walk-ins welcome for diagnostics — appointments recommended for repairs.",
    hoursNote: "Shop hours: Monday – Saturday, 7:30 AM – 6:00 PM",
    towingLabel: "24/7 Towing",
  };
}
