import { Scissors, Sparkles, Brush, Crown } from "lucide-react";
import { barbershop as img } from "./images";
import type { DemoLocale } from "@/lib/demo-i18n/LanguageContext";

export const barbershopShared = {
  icon: Scissors,
  theme: { accent: "#eab308", accent2: "#a16207" },
  phone: "(514) 555-0121",
  email: "book@salon-demo.com",
  address: "3455 Boulevard Saint-Laurent, Montreal, QC H2X 2T6",
};

export const barbershopContent: Record<DemoLocale, ReturnType<typeof buildFr> | ReturnType<typeof buildEn>> = {
  fr: buildFr(),
  en: buildEn(),
};

function buildFr() {
  return {
    businessName: "Salon de coiffure",
    tagline: "Une vision moderne du salon de coiffure classique — coupes précises, rasage à la serviette chaude et une ambiance pensée pour vous.",
    ctaLabel: "Réserver maintenant",
    navLinks: [
      { label: "Services", href: "#services" },
      { label: "Coiffeurs", href: "#barbers" },
      { label: "Prix", href: "#prices" },
      { label: "Réserver", href: "#booking" },
      { label: "Galerie", href: "#gallery" },
      { label: "Avis", href: "#reviews" },
      { label: "Horaires", href: "#hours" },
      { label: "Contact", href: "#contact" },
    ],
    hero: {
      eyebrow: "Fondé en 2016 · Vieux-Montréal",
      title: "Coupes précises. Savoir-faire classique.",
      subtitle: "Un salon de coiffure moderne où chaque visite est à la fois une coupe et un rituel.",
      imageId: img.heroWide,
      primaryCta: { label: "Prendre rendez-vous", href: "#booking" },
      secondaryCta: { label: "Voir nos réalisations", href: "#gallery" },
    },
    servicesEyebrow: "Nos services",
    servicesTitle: "Pensé pour l'homme moderne",
    services: [
      { icon: Scissors, title: "Coupe signature", description: "Coupe précise, consultation et coiffage final — notre service le plus populaire." },
      { icon: Brush, title: "Rasage à la serviette chaude", description: "Un rasage traditionnel au rasoir droit avec préparation à la serviette chaude et baume final." },
      { icon: Sparkles, title: "Taille de barbe", description: "Forme, taille et contour adaptés à votre visage et à votre pilosité." },
      { icon: Crown, title: "L'expérience complète", description: "Coupe, rasage à la serviette chaude et taille de barbe en une session de 90 minutes." },
    ],
    barbersEyebrow: "Notre équipe",
    barbersTitle: "Nos maîtres coiffeurs",
    barbers: [
      { name: "Antoine Dubois", role: "Maître coiffeur et propriétaire", bio: "15 ans d'expérience, formé à Montréal et à Londres." },
      { name: "Marcus Webb", role: "Coiffeur senior", bio: "Spécialiste des dégradés modernes et des pompadours classiques." },
      { name: "Elias Cormier", role: "Coiffeur", bio: "Reconnu pour son travail de barbe minutieux et ses rasages au rasoir droit." },
    ],
    pricesEyebrow: "Liste de prix",
    pricesTitle: "Des prix simples et transparents",
    prices: [
      { name: "Coupe signature", price: "45 $", features: ["Consultation et lavage inclus"] },
      { name: "Rasage à la serviette chaude", price: "40 $", features: ["Rasoir droit, préparation à la serviette chaude"] },
      { name: "Taille de barbe", price: "30 $", features: ["Forme, taille et contour"] },
      { name: "L'expérience complète", price: "95 $", features: ["Coupe, rasage et barbe, 90 minutes"] },
      { name: "Coupe enfant (12 ans et moins)", price: "25 $", features: ["Le même service de qualité, à prix réduit"] },
    ],
    bookingEyebrow: "Réserver",
    bookingTitle: "Réservez votre place",
    bookingDescription: "Choisissez votre service, votre coiffeur et l'heure — nous confirmerons par texto.",
    bookingFields: [
      { type: "text" as const, name: "name", label: "Nom complet", placeholder: "Votre nom", required: true, span: 1 as const },
      { type: "tel" as const, name: "phone", label: "Téléphone", placeholder: "(514) 000-0000", required: true, span: 1 as const },
      {
        type: "select" as const,
        name: "service",
        label: "Service",
        options: ["Coupe signature", "Rasage à la serviette chaude", "Taille de barbe", "L'expérience complète", "Coupe enfant"],
        span: 1 as const,
      },
      {
        type: "select" as const,
        name: "barber",
        label: "Coiffeur préféré",
        options: ["Aucune préférence", "Antoine Dubois", "Marcus Webb", "Elias Cormier"],
        span: 1 as const,
      },
      { type: "date" as const, name: "date", label: "Date préférée", span: 1 as const },
      { type: "time" as const, name: "time", label: "Heure préférée", span: 1 as const },
    ],
    bookingSubmitLabel: "Demander un rendez-vous",
    bookingSuccess: "C'est réservé! Nous confirmerons votre rendez-vous par texto sous peu.",
    galleryEyebrow: "Notre savoir-faire",
    galleryTitle: "Réalisations récentes",
    gallery: [
      { imageId: img.precisionCut, caption: "Dégradé précis" },
      { imageId: img.beardGrooming, caption: "Taille de barbe" },
      { imageId: img.clientInChair, caption: "L'expérience en fauteuil" },
      { imageId: img.vintageChairBrick, caption: "Notre intérieur" },
      { imageId: img.modernChair, caption: "Postes de coiffage modernes" },
      { imageId: img.storefront, caption: "Notre devanture" },
    ],
    reviewsEyebrow: "Avis clients",
    reviewsTitle: "Ce que disent nos clients",
    reviews: [
      { quote: "Le meilleur dégradé que j'ai eu à Montréal, sans hésitation. Antoine est un vrai artisan.", name: "Julien Fortin", role: "Avis Google", rating: 5 },
      { quote: "Le rasage à la serviette chaude vaut à lui seul la visite. Belle ambiance, sans précipitation.", name: "Marc Villeneuve", role: "Avis Google", rating: 5 },
      { quote: "Réservé en ligne en quelques secondes, entré et sorti avec une coupe parfaite. Mon nouvel endroit régulier.", name: "Chris Okafor", role: "Avis Google", rating: 5 },
    ],
    hoursNote: "Sans rendez-vous bienvenu, mais rendez-vous recommandé.",
    hours: [
      { day: "Lundi", hours: "Fermé" },
      { day: "Mardi – Vendredi", hours: "10 h – 20 h" },
      { day: "Samedi", hours: "9 h – 18 h" },
      { day: "Dimanche", hours: "11 h – 16 h" },
    ],
    contactEyebrow: "Nous joindre",
    contactTitle: "Trouvez votre coiffeur",
  };
}

function buildEn() {
  return {
    businessName: "Hair Salon",
    tagline: "A modern take on the classic barbershop — precision cuts, hot towel shaves, and an atmosphere built for gentlemen.",
    ctaLabel: "Book Now",
    navLinks: [
      { label: "Services", href: "#services" },
      { label: "Barbers", href: "#barbers" },
      { label: "Prices", href: "#prices" },
      { label: "Book Now", href: "#booking" },
      { label: "Gallery", href: "#gallery" },
      { label: "Reviews", href: "#reviews" },
      { label: "Hours", href: "#hours" },
      { label: "Contact", href: "#contact" },
    ],
    hero: {
      eyebrow: "Est. 2016 · Old Montreal",
      title: "Precision cuts. Classic craft.",
      subtitle: "A modern gentlemen's barbershop where every visit is part haircut, part ritual.",
      imageId: img.heroWide,
      primaryCta: { label: "Book an Appointment", href: "#booking" },
      secondaryCta: { label: "See Our Work", href: "#gallery" },
    },
    servicesEyebrow: "Our Services",
    servicesTitle: "Crafted for the modern gentleman",
    services: [
      { icon: Scissors, title: "Signature Haircut", description: "Precision cut, consultation, and finish styling — our most popular service." },
      { icon: Brush, title: "Hot Towel Shave", description: "A traditional straight-razor shave with hot towel prep and finishing balm." },
      { icon: Sparkles, title: "Beard Sculpting", description: "Shape, trim, and line-up tailored to your face and growth pattern." },
      { icon: Crown, title: "The Full Experience", description: "Haircut, hot towel shave, and beard sculpt in one relaxed 90-minute session." },
    ],
    barbersEyebrow: "Meet The Team",
    barbersTitle: "Our master barbers",
    barbers: [
      { name: "Antoine Dubois", role: "Master Barber & Owner", bio: "15 years of experience, trained in Montreal and London." },
      { name: "Marcus Webb", role: "Senior Barber", bio: "Specialist in modern fades and classic pompadours." },
      { name: "Elias Cormier", role: "Barber", bio: "Known for detailed beard work and straight-razor shaves." },
    ],
    pricesEyebrow: "Price List",
    pricesTitle: "Simple, transparent pricing",
    prices: [
      { name: "Signature Haircut", price: "$45", features: ["Consultation & wash included"] },
      { name: "Hot Towel Shave", price: "$40", features: ["Straight razor, hot towel prep"] },
      { name: "Beard Sculpting", price: "$30", features: ["Shape, trim & line-up"] },
      { name: "The Full Experience", price: "$95", features: ["Cut, shave & beard, 90 minutes"] },
      { name: "Kids Cut (12 & under)", price: "$25", features: ["Same great service, smaller price"] },
    ],
    bookingEyebrow: "Book Now",
    bookingTitle: "Reserve your chair",
    bookingDescription: "Pick your service, barber, and time — we'll confirm by text.",
    bookingFields: [
      { type: "text" as const, name: "name", label: "Full Name", placeholder: "Your name", required: true, span: 1 as const },
      { type: "tel" as const, name: "phone", label: "Phone", placeholder: "(514) 000-0000", required: true, span: 1 as const },
      {
        type: "select" as const,
        name: "service",
        label: "Service",
        options: ["Signature Haircut", "Hot Towel Shave", "Beard Sculpting", "The Full Experience", "Kids Cut"],
        span: 1 as const,
      },
      {
        type: "select" as const,
        name: "barber",
        label: "Preferred Barber",
        options: ["No preference", "Antoine Dubois", "Marcus Webb", "Elias Cormier"],
        span: 1 as const,
      },
      { type: "date" as const, name: "date", label: "Preferred Date", span: 1 as const },
      { type: "time" as const, name: "time", label: "Preferred Time", span: 1 as const },
    ],
    bookingSubmitLabel: "Request Appointment",
    bookingSuccess: "You're booked! We'll confirm your appointment by text shortly.",
    galleryEyebrow: "Our Craft",
    galleryTitle: "Recent work",
    gallery: [
      { imageId: img.precisionCut, caption: "Precision Fade" },
      { imageId: img.beardGrooming, caption: "Beard Sculpting" },
      { imageId: img.clientInChair, caption: "The Chair Experience" },
      { imageId: img.vintageChairBrick, caption: "Our Interior" },
      { imageId: img.modernChair, caption: "Modern Styling Stations" },
      { imageId: img.storefront, caption: "Our Storefront" },
    ],
    reviewsEyebrow: "Client Reviews",
    reviewsTitle: "What our clients say",
    reviews: [
      { quote: "Best fade I've had in Montreal, period. Antoine is a true craftsman.", name: "Julien Fortin", role: "Google Review", rating: 5 },
      { quote: "The hot towel shave is worth it alone. Great atmosphere, no rush.", name: "Marc Villeneuve", role: "Google Review", rating: 5 },
      { quote: "Booked online in seconds, in and out with a perfect cut. My new regular spot.", name: "Chris Okafor", role: "Google Review", rating: 5 },
    ],
    hoursNote: "Walk-ins welcome, but appointments are recommended.",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday – Friday", hours: "10:00 AM – 8:00 PM" },
      { day: "Saturday", hours: "9:00 AM – 6:00 PM" },
      { day: "Sunday", hours: "11:00 AM – 4:00 PM" },
    ],
    contactEyebrow: "Get In Touch",
    contactTitle: "Find your barber",
  };
}
